#!/bin/bash
#
# Compare the screening coefficients alpha from the model dielectric functions
# (this example) with the ab-initio linear-response ones (example01/reference),
# and write the gnuplot script compare_bands.gnu comparing the KI band structures.
# The model results are taken from results/ if available, otherwise from reference/.
#
cd `dirname $0`

LR_FILE=../example01/reference/Si.kcw-screen.out
MODELS="gaussian cappellini"

if [ ! -r $LR_FILE ]; then
   echo "ERROR: $LR_FILE not found"
   exit 1
fi

# alpha is the 12th field of the "iwann = ... relaxed = ... alpha = ..." lines
get_alpha () { grep "relaxed =" $1 | awk '{print $12}'; }

ALPHA_LR=( `get_alpha $LR_FILE` )
NWANN=${#ALPHA_LR[@]}

declare -A ALPHA
for MODEL in $MODELS; do
   FILE=results/Si.kcw-screen_$MODEL.out
   if [ ! -r $FILE ]; then FILE=reference/Si.kcw-screen_$MODEL.out; fi
   if [ ! -r $FILE ]; then
      echo "ERROR: no output found for the $MODEL model"
      exit 1
   fi
   echo "  $MODEL: $FILE"
   i=0
   for a in `get_alpha $FILE`; do ALPHA[$MODEL,$i]=$a; i=$((i+1)); done
   if [ $i -ne $NWANN ]; then
      echo "ERROR: $FILE has $i alphas, $LR_FILE has $NWANN"
      exit 1
   fi
done
echo "  LR: $LR_FILE"
echo

# Header
printf "  %5s  %10s" "iwann" "LR"
for MODEL in $MODELS; do printf "  %10s  %8s" "$MODEL" "diff(%)"; done
printf "\n"

# One line per Wannier function: alpha and relative difference wrt LR
for i in `seq 0 $((NWANN-1))`; do
   printf "  %5d  %10.6f" $((i+1)) ${ALPHA_LR[$i]}
   for MODEL in $MODELS; do
      a=${ALPHA[$MODEL,$i]}
      d=`echo $a ${ALPHA_LR[$i]} | awk '{printf "%8.1f", 100*($1-$2)/$2}'`
      printf "  %10.6f  %8s" $a "$d"
   done
   printf "\n"
done

#################### Band gaps from the interpolated KI band structures
LR_BANDS=../example01/reference/Si.kcw_bands.dat
NOCC=4   # number of occupied bands (num_wann_occ)

# Bands are separated by blank lines; x=0 is Gamma. Prints:
# minimum gap, x of VBM, x of CBM, gap at Gamma
get_gaps () {
   awk -v nocc=$NOCC '
      BEGIN { b=1; vbm=-1e10; cbm=1e10 }
      NF==0 { if (n>0) b++; n=0; next }
      { n++
        if (b==nocc   && $2>vbm) { vbm=$2; xv=$1 }
        if (b==nocc+1 && $2<cbm) { cbm=$2; xc=$1 }
        if (n==1 && b==nocc)   vg=$2
        if (n==1 && b==nocc+1) cg=$2 }
      END { printf "%.4f %.4f %.4f %.4f", cbm-vbm, xv, xc, cg-vg }' $1
}

declare -A GAP
read GAP[LR,min] GAP[LR,xv] GAP[LR,xc] GAP[LR,G] <<< `get_gaps $LR_BANDS`
for MODEL in $MODELS; do
   BANDS=results/Si.kcw_bands_$MODEL.dat
   if [ ! -r $BANDS ]; then BANDS=reference/Si.kcw_bands_$MODEL.dat; fi
   read GAP[$MODEL,min] GAP[$MODEL,xv] GAP[$MODEL,xc] GAP[$MODEL,G] <<< `get_gaps $BANDS`
done

echo
echo "  KI band gaps (eV) along the k-path of the band structure"
echo "  (x = position along the path, Gamma at x=0)"
printf "  %-12s  %10s  %8s  %8s  %10s\n" "" "min gap" "x(VBM)" "x(CBM)" "gap(Gamma)"
for M in LR $MODELS; do
   printf "  %-12s  %10.4f  %8.4f  %8.4f  %10.4f\n" $M ${GAP[$M,min]} ${GAP[$M,xv]} ${GAP[$M,xc]} ${GAP[$M,G]}
done
echo
echo "  Difference wrt LR (eV)"
printf "  %-12s  %10s  %10s\n" "" "min gap" "gap(Gamma)"
for MODEL in $MODELS; do
   d1=`echo ${GAP[$MODEL,min]} ${GAP[LR,min]} | awk '{printf "%+.4f", $1-$2}'`
   d2=`echo ${GAP[$MODEL,G]} ${GAP[LR,G]} | awk '{printf "%+.4f", $1-$2}'`
   printf "  %-12s  %10s  %10s\n" $MODEL $d1 $d2
done

#################### Band structures: write a gnuplot script
GNU=compare_bands.gnu

# k-path of the example: points per segment (as in K_POINTS) and vertex labels
NPTS="10 10 1 10 10 10 10"
LABELS="Γ X U K Γ L W X"

# x coordinate of each vertex, from the first band of the LR file
XTICS=`awk -v npts="$NPTS" -v labels="$LABELS" '
   BEGIN { nseg=split(npts,n," "); split(labels,l," ");
           idx[1]=1; for (s=1; s<=nseg; s++) idx[s+1]=idx[s]+n[s] }
   NF==0 { exit }
   { x[++i]=$1 }
   END { nt=0
         for (s=1; s<=nseg+1; s++) {
            xs=x[idx[s]]
            if (nt>0 && xs==tx[nt]) { tl[nt]=tl[nt] "|" l[s]; continue }  # e.g. U|K: same x
            nt++; tx[nt]=xs; tl[nt]=l[s] }
         for (t=1; t<=nt; t++) printf "%s\"%s\" %s", (t>1 ? ", " : ""), tl[t], tx[t] }' $LR_BANDS`
XMAX=`awk 'NF==0{exit} {x=$1} END{print x}' $LR_BANDS`

cat > $GNU << EOF
# KI band structure of Si: model screening vs ab-initio LR (example01)
# Generated by compare_LR.sh. Run with: gnuplot $GNU
set encoding utf8
set xtics ($XTICS)
set grid xtics lt -1 lw 0.5
set xrange [0:$XMAX]
set ylabel "Energy (eV)"
set key outside top center horizontal
EOF

COLOR_gaussian="red"
COLOR_cappellini="blue"
for MODEL in $MODELS; do
   BANDS=results/Si.kcw_bands_$MODEL.dat
   if [ ! -r $BANDS ]; then BANDS=reference/Si.kcw_bands_$MODEL.dat; fi
   eval BANDS_$MODEL=$BANDS
   eval COLOR=\$COLOR_$MODEL
   cat >> $GNU << EOF

set title "Si KI bands: $MODEL model vs LR"
plot "$LR_BANDS" w l lc rgb "black" lw 2 t "LR (example01)", \\
     "$BANDS"    w l lc rgb "$COLOR" lw 2 dt 2 t "$MODEL"
pause -1 "Press Enter for the next plot"
EOF
done

cat >> $GNU << EOF

set title "Si KI bands: all models vs LR"
plot "$LR_BANDS"          w l lc rgb "black" lw 2 t "LR (example01)", \\
     "$BANDS_gaussian"    w l lc rgb "$COLOR_gaussian" lw 2 dt 2 t "gaussian", \\
     "$BANDS_cappellini"  w l lc rgb "$COLOR_cappellini" lw 2 dt 3 t "cappellini"
pause -1 "Press Enter to exit"
EOF

echo
echo "  Band structure comparison written to $GNU. Run with: gnuplot $GNU"
