! Copyright (C) 2003-2024 Quantum ESPRESSO group
! This file is distributed under the terms of the
! GNU General Public License. See the file `License'
! in the root directory of the present distribution,
! or http://www.gnu.org/copyleft/gpl.txt .
!
#define ZERO CMPLX(0.D0,0.D0,kind=DP)
!-----------------------------------------------------------------------
SUBROUTINE screen_coeff_model ()
  !---------------------------------------------------------------------
  !
  !! Screening coefficients from a model dielectric function (no LR calculation).
  !! The model is diagonal in G (see PRR 2, 032019(R) (2020); PRR 2, 073803 (2018)):
  !!
  !!   eps^{-1}_q(G) = 1 - (1 - 1/eps_inf) * exp(-|q+G|^2/(4 mu^2))
  !!
  !! and the screening coefficient is
  !!
  !!   alpha_n = \sum_q <rho^{0n}_q | eps^{-1}_q dV^{0n}_q> / \sum_q <rho^{0n}_q | dV^{0n}_q>
  !!
  !! with dV^{0n}_q the Hxc potential generated by the Wannier density (see bare_pot).
  !! The denominator is the unrelaxed uPi of screen_coeff. For q+G=0 eps^{-1} -> 1/eps_inf
  !! and the Hartree contribution is the screened divergence exxdiv_eps (see setup_coulomb).
  !
  USE kinds,                ONLY : DP
  USE fft_base,             ONLY : dffts, dfftp
  USE mp,                   ONLY : mp_sum
  USE control_kcw,          ONLY : spin_component, num_wann, iorb_start, l_do_alpha, &
                                   iorb_end, alpha_final, nqstot, eps_inf, mu_screen, &
                                   group_alpha, tmp_dir_kcw, iurho_wann, x_q, &
                                   i_orb, nrho, irr_bz
  USE noncollin_module,     ONLY : nspin_mag
  USE buffers,              ONLY : get_buffer
  USE io_global,            ONLY : stdout
  USE mp_bands,             ONLY : intra_bgrp_comm
  USE lsda_mod,             ONLY : nspin
  USE gvect,                ONLY : g
  USE gvecs,                ONLY : ngms
  USE io_files,             ONLY : prefix
  USE qpoint,               ONLY : xq
  USE control_lr,           ONLY : lgamma
  USE eqv,                  ONLY : dmuxc
  USE gc_lr,                ONLY : grho, gmag, dvxc_rr, dvxc_sr, dvxc_ss, &
                                   dvxc_s, vsgga, segni
  USE coulomb,              ONLY : exxdiv, exxdiv_eps
  USE cell_base,            ONLY : omega, tpiba2
  !
  IMPLICIT NONE
  !
  INTEGER :: iq, nqs, iwann, jwann, lrrho, ig, ip
  !
  COMPLEX(DP), ALLOCATABLE :: rhowann(:,:,:), rhor(:,:), delta_vr(:,:), delta_vr_(:,:)
  COMPLEX(DP), ALLOCATABLE :: rhog(:,:), delta_vg(:,:), delta_vg_(:,:), vh_rhog(:)
  ! wannier density (r and G), perturbing potential w and w/o the q+G=0 Hartree term, hartree potential
  !
  COMPLEX(DP), ALLOCATABLE :: vki_u(:), vki_r(:), sh(:)
  ! unrelaxed (bare) and model-screened Hxc matrix elements, self-hartree
  !
  REAL(DP), ALLOCATABLE :: epsm1(:)
  ! the model inverse dielectric function eps^{-1}_q(G)
  !
  COMPLEX(DP) :: pi_q_unrelax, pi_q_model, sh_q
  REAL(DP) :: qg2, weight, alpha
  !
  IF ( ABS(eps_inf - 1.D0) .lt. 1.D-6 ) &
     CALL errore('screen_coeff_model', 'eps_inf = 1: the model screening is trivial (alpha=1). Set eps_inf', 1)
  IF ( mu_screen .le. 0.D0 ) &
     CALL errore('screen_coeff_model', 'mu_screen must be > 0', 1)
  !
  nqs = nqstot
  weight = 1.D0/nqs
  !
  WRITE(stdout,'(/)')
  WRITE(stdout,'(5X,"INFO: MODEL SCREENING CALCULATION ...")')
  WRITE(stdout,'(5X,"INFO: eps^-1_q(G) = 1 - (1 - 1/eps_inf) exp(-|q+G|^2/4mu^2)")')
  WRITE(stdout,'(5X,"INFO: eps_inf   = ", F12.6)') eps_inf
  WRITE(stdout,'(5X,"INFO: mu_screen = ", F12.6, "  [bohr^-1]")') mu_screen
  IF (irr_bz) WRITE(stdout,'(5X,"INFO: irr_bz ignored, sum over the full BZ")')
  !
  ALLOCATE ( rhowann(dffts%nnr,num_wann,nrho), rhor(dffts%nnr,nrho) )
  ALLOCATE ( delta_vr(dffts%nnr,nspin_mag), delta_vr_(dffts%nnr,nspin_mag) )
  ALLOCATE ( rhog(ngms,nrho), delta_vg(ngms,nspin_mag), delta_vg_(ngms,nspin_mag), vh_rhog(ngms) )
  ALLOCATE ( epsm1(ngms) )
  ALLOCATE ( vki_u(num_wann), vki_r(num_wann), sh(num_wann) )
  vki_u = ZERO
  vki_r = ZERO
  sh    = ZERO
  !
  ! ... The xc kernel does not depend on q: set it up once (see kcw_q_setup)
  ALLOCATE ( dmuxc(dfftp%nnr,nspin_mag,nspin_mag) )
  CALL setup_dmuxc()
  CALL setup_dgc()
  !
  !$acc enter data create(rhor, rhog, vh_rhog, delta_vr, delta_vr_, delta_vg, delta_vg_)
  !
  DO iq = 1, nqs
    !
    xq(:) = x_q(:,iq)
    lgamma = ( xq(1) == 0.D0 .AND. xq(2) == 0.D0 .AND. xq(3) == 0.D0 )
    !
    lrrho = num_wann*dffts%nnr*nrho
    CALL get_buffer (rhowann, lrrho, iurho_wann, iq)
    !
    ! ... The model inverse dielectric function at this q
    DO ig = 1, ngms
      qg2 = tpiba2 * SUM( (g(:,ig)+x_q(:,iq))**2 )
      epsm1(ig) = 1.D0 - (1.D0 - 1.D0/eps_inf) * EXP( -qg2/(4.D0*mu_screen**2) )
    ENDDO
    !
    DO iwann = iorb_start, iorb_end
      !
      IF ( .NOT. l_do_alpha (iwann)) CYCLE
      !
      rhor(:,:) = rhowann(:,iwann,:)
      !$acc update device(rhor)
      CALL bare_pot ( rhor, rhog, vh_rhog, delta_vr, delta_vg, iq, delta_vr_, delta_vg_ )
      !$acc update self(rhog, vh_rhog, delta_vg, delta_vg_)
      !
      pi_q_unrelax = ZERO
      pi_q_model   = ZERO
      sh_q         = ZERO
      !
      IF (nspin == 4) THEN
        DO ip = 1, nspin_mag
          DO ig = 1, ngms
            pi_q_unrelax = pi_q_unrelax + CONJG(rhog(ig,ip)) * delta_vg(ig,ip)
            pi_q_model   = pi_q_model   + CONJG(rhog(ig,ip)) * epsm1(ig) * delta_vg_(ig,ip)
          ENDDO
        ENDDO
      ELSE
        DO ig = 1, ngms
          pi_q_unrelax = pi_q_unrelax + CONJG(rhog(ig,1)) * delta_vg(ig,spin_component)
          pi_q_model   = pi_q_model   + CONJG(rhog(ig,1)) * epsm1(ig) * delta_vg_(ig,spin_component)
        ENDDO
      ENDIF
      !
      DO ig = 1, ngms
        sh_q = sh_q + CONJG(rhog(ig,1)) * vh_rhog(ig)
        ! ... The screened Hartree q+G=0 term (zero if l_vcut=.false.)
        qg2 = SUM( (g(:,ig)+x_q(:,iq))**2 )
        IF (qg2 .lt. 1.0e-8_dp) pi_q_model = pi_q_model + CONJG(rhog(ig,1)) * (-exxdiv_eps) * rhog(ig,1)
      ENDDO
      !
      pi_q_unrelax = pi_q_unrelax * weight * omega
      pi_q_model   = pi_q_model   * weight * omega
      sh_q         = 0.5_dp * sh_q * weight * omega
      !
      CALL mp_sum (pi_q_unrelax, intra_bgrp_comm)
      CALL mp_sum (pi_q_model,   intra_bgrp_comm)
      CALL mp_sum (sh_q,         intra_bgrp_comm)
      !
      WRITE(stdout, 9011) iq, iwann, pi_q_model, pi_q_unrelax, sh_q
      !
      vki_u(iwann) = vki_u(iwann) + pi_q_unrelax
      vki_r(iwann) = vki_r(iwann) + pi_q_model
      sh(iwann)    = sh(iwann)    + sh_q
      !
    ENDDO
    !
  ENDDO ! qpoints
  !
  !$acc exit data delete(rhor, rhog, vh_rhog, delta_vr, delta_vr_, delta_vg, delta_vg_)
  !
  WRITE(stdout,'(/)')
  WRITE(stdout,'(5X,"INFO: MODEL SCREENING CALCULATION ... DONE")')
  WRITE(stdout,'(/)')
  !
  IF ( i_orb == -1 ) THEN
    OPEN (876, file = TRIM(tmp_dir_kcw)//TRIM(prefix)//'.alpha.dat')
    WRITE(876,'(i5)') num_wann
  ENDIF
  !
  DO jwann = iorb_start, iorb_end
    !
    iwann = group_alpha(jwann)
    alpha = REAL(vki_r(iwann))/REAL(vki_u(iwann))
    !
    IF ( l_do_alpha(jwann) ) THEN
      WRITE(stdout,'(/, 8x, "iwann  = ", i5, 3x, "relaxed = ", 1f15.8, 3x, "unrelaxed = " &
                &  , 1f15.8, 3x, "alpha =", f12.8, 3x, "self Hartree =", f12.8 )') &
                &  jwann, REAL(vki_r(iwann)), REAL(vki_u(iwann)), alpha, REAL(sh(iwann))
    ELSE
      WRITE(stdout,'(/, 8x, "iwann* = ", i5, 3x, "relaxed = ", 1f15.8, 3x, "unrelaxed = " &
                 &  , 1f15.8, 3x, "alpha =", f12.8, 3x, "self Hartree =", f12.8 )') &
                 &  jwann, REAL(vki_r(iwann)), REAL(vki_u(iwann)), alpha, REAL(sh(iwann))
    ENDIF
    !
    alpha_final(iwann) = alpha
    IF (i_orb == -1) WRITE(876,'(i5, 2(3x, F16.12))') iwann, alpha, REAL(sh(iwann))
    !
  ENDDO
  !
  WRITE(stdout, '(3/)')
  IF ( i_orb == -1 ) CLOSE (876)
  !
  DEALLOCATE ( rhowann, rhor, delta_vr, delta_vr_ )
  DEALLOCATE ( rhog, delta_vg, delta_vg_, vh_rhog, epsm1 )
  DEALLOCATE ( vki_u, vki_r, sh )
  !
  IF (ALLOCATED(dmuxc))   DEALLOCATE (dmuxc)
  IF (ALLOCATED(dvxc_rr)) DEALLOCATE (dvxc_rr)
  IF (ALLOCATED(dvxc_sr)) DEALLOCATE (dvxc_sr)
  IF (ALLOCATED(dvxc_ss)) DEALLOCATE (dvxc_ss)
  IF (ALLOCATED(dvxc_s))  DEALLOCATE (dvxc_s)
  IF (ALLOCATED(grho))    DEALLOCATE (grho)
  IF (ALLOCATED(segni))   DEALLOCATE (segni)
  IF (ALLOCATED(vsgga))   DEALLOCATE (vsgga)
  IF (ALLOCATED(gmag))    DEALLOCATE (gmag)
  !
  CALL kcw_deallocate_symmetry_arrays()
  !
9011 FORMAT(/, 8x, "iq =", i4, 3x, "iwann =", i4, 3x, "rPi_q =", 2f15.8, 3x, "uPi_q =", &
               2f15.8, 3x, "SH_q =", 2f15.8)
  !
END SUBROUTINE screen_coeff_model
